"console_admin_password" = "theYorkshireAllen123!"
"puppet_enterprise::puppet_master_host" = "pe-primary"
"puppet_enterprise::certname" = "pe-primary"
"puppet_enterprise::profile::master::code_manager_auto_configure" = true
"puppet_enterprise::profile::master::r10k_remote" = "https://github.com/the-yorkshire-allen/pe-rbac.git"
"puppet_enterprise::profile::master::r10k_private_key" = "/etc/puppetlabs/keys/r10k-deploy-key"
"puppet_enterprise::profile::master::r10k_remote_timeout" = 60
